/** Example placeholders for agent onboarding — hints only, not submitted as values */

export const P = {
  name: 'e.g. Nkurunziza',
  firstName: 'e.g. Jean',
  surname: 'e.g. Habimana',
  otherNames: 'e.g. Pierre',
  phone: 'e.g. +250 788 000 000',
  nid: 'e.g. 1199080123456789',
  district: 'e.g. Nyagatare',
  sector: 'e.g. Rwimiyaga',
  cell: 'e.g. Cell name',
  village: 'e.g. Village name',
  province: 'e.g. Eastern Province',
  km: 'e.g. 8',
  whoOther: 'e.g. hired motorbike',
  coopNum: 'e.g. 12',
  totalCows: 'e.g. 25',
  breedCount: 'e.g. 5',
  lactating: 'e.g. 4',
  litersPerCow: 'e.g. 12.5',
  litersDay: 'e.g. 180',
  litersDayLow: 'e.g. 120',
  mccName: 'e.g. Karama MCC',
  months: 'e.g. 13',
  hectares: 'e.g. 2.5',
  workers: 'e.g. 3',
  women: 'e.g. 1',
  youth: 'e.g. 2',
  revenue: 'e.g. 3500000',
  notes: 'e.g. follow up on vet visit',
  reason: 'e.g. transport delay',
  managerName: 'e.g. Marie Uwimana',
  managerAge: 'e.g. 42',
  grantSource: 'e.g. government programme',
  insurance: 'e.g. SONARWA',
  transitMin: 'e.g. 45',
  radiusKm: 'e.g. 15',
  farmCount: 'e.g. 8',
  rosterName: 'e.g. farm / Gemura ID',
  transportOther: 'e.g. bicycle with cans',
  coolingDetail: 'e.g. insulated cans, 40L',
  lat: 'e.g. -1.943',
  lng: 'e.g. 29.873',
  trainingProvider: 'e.g. RAB / district extension',
  grantProvided: 'e.g. subsidised AI vouchers',
  pwdCount: 'e.g. 0',
} as const;
